import { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '@/lib/types';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  fr: {
    'nav.home': 'Accueil',
    'nav.demo': 'Démo gratuite',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',
    'nav.dashboard': 'Tableau de bord',
    'nav.logout': 'Déconnexion',
    'nav.pricing': 'Tarifs',
    'nav.about': 'À propos',
    'hero.title': 'Préparez votre examen de citoyenneté',
    'hero.subtitle': 'La plateforme officielle pour réussir votre examen civique français en 2026',
    'hero.cta': 'Démo gratuite',
    'hero.cta2': 'Voir les prix',
    'pricing.title': 'Tarifs simples et transparents',
    'pricing.monthly': 'Mensuel',
    'pricing.semester': '6 Mois',
    'pricing.monthly.price': '6,99 €',
    'pricing.semester.price': '30,99 €',
    'pricing.feature1': 'Accès à toutes les questions',
    'pricing.feature2': 'Mode examen et étude',
    'pricing.feature3': 'Suivi de progression',
    'pricing.feature4': 'Questions bilingues',
    'pricing.cta': 'Commencer',
    'pricing.save': 'Économisez 26%',
    'pricing.free': 'Gratuit',
    'pricing.recommended': 'Recommandé',
    'pricing.ctaFree': 'Créer un compte',
    'pricing.ctaStandard': 'Choisir Standard',
    'pricing.ctaPremium': 'Choisir Premium',
    'pricing.feat.browse': 'Parcourir le site',
    'pricing.feat.demo': '1 examen démo',
    'pricing.feat.unlimited': 'Examens illimités',
    'pricing.feat.training': 'Mode entraînement',
    'pricing.feat.progress': 'Suivi de progression',
    'pricing.feat.lessons': 'Accès aux leçons',
    'pricing.feat.path': 'Parcours d\'apprentissage',
    'pricing.feat.translation': 'Traduction des questions',
    'pricing.feat.catTraining': 'Entraînement par catégorie',
    'quiz.question': 'Question',
    'quiz.of': 'sur',
    'quiz.next': 'Suivante',
    'quiz.prev': 'Précédente',
    'quiz.finish': 'Terminer',
    'quiz.timeRemaining': 'Temps restant',
    'quiz.study': 'Mode étude',
    'quiz.exam': 'Mode examen',
    'quiz.explanation': 'Explication',
    'quiz.correct': 'Bonne réponse !',
    'quiz.incorrect': 'Mauvaise réponse',
    'results.title': 'Résultats de l\'examen',
    'results.passed': 'RÉUSSI',
    'results.failed': 'ÉCHOUÉ',
    'results.score': 'Score',
    'results.time': 'Temps',
    'results.categories': 'Par catégorie',
    'results.retry': 'Réessayer',
    'results.home': 'Retour à l\'accueil',
    'results.passThreshold': 'Seuil de réussite : 80%',
    'auth.login': 'Connexion',
    'auth.signup': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.google': 'Continuer avec Google',
    'auth.or': 'ou',
    'auth.noAccount': 'Pas de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.resetPassword': 'Réinitialiser le mot de passe',
    'auth.resetSent': 'Email envoyé ! Vérifiez votre boîte de réception.',
    'auth.backToLogin': 'Retour à la connexion',
    'footer.rights': '© 2026 GoCivique. Tous droits réservés.',
    'footer.disclaimer': 'Ce site n\'est pas affilié au gouvernement français. Il s\'agit d\'une plateforme d\'entraînement privée pour l\'Examen Civique.',
    // Category descriptions
    'cat.Principles.desc': 'Liberté, Égalité, Fraternité — Laïcité, symboles et valeurs fondamentales.',
    'cat.Institutions.desc': 'Président, Parlement, Justice — l\'organisation de l\'État français.',
    'cat.Rights.desc': 'Droits fondamentaux, devoirs civiques et libertés garanties par la République.',
    'cat.History.desc': 'Périodes clés, patrimoine culturel et géographie de la France.',
    'cat.Living.desc': 'Santé, éducation, travail — la vie quotidienne en France.',
    'cat.Politics.desc': 'Système politique, partis et participation citoyenne.',
    'cat.Society.desc': 'Cohésion sociale, diversité et vivre-ensemble.',
    'cat.explore': 'Explorez les catégories',
    'cat.exploreSubtitle': 'Préparez chaque domaine de l\'examen de citoyenneté avec des quiz ciblés.',
    'cat.study': 'S\'entraîner',
    // Progress section
    'progress.title': 'Suivez votre progression',
    'progress.titleAuth': 'Votre progression',
    'progress.subtitleGuest': 'Créez un compte pour suivre votre progression et vos statistiques.',
    'progress.subtitleAuth': 'Basée sur vos résultats d\'examens',
    'progress.createAccount': 'Créer un compte',
    'progress.passProbability': 'Probabilité de réussite',
    'progress.basedOnLast5': 'Basée sur les 5 derniers examens',
    'progress.examsTaken': 'Examens passés',
    'progress.avgScore': 'Score moyen',
    'progress.officialThreshold': 'Seuil officiel',
    'progress.bankProgress': 'Progression dans la banque',
    // Dashboard
    'dash.dashboard': 'Tableau de bord',
    'dash.overallProgress': 'Progression globale',
    'dash.currentStatus': 'Statut actuel',
    'dash.onTrack': 'En bonne voie',
    'dash.needsPractice': 'Entraînement nécessaire',
    'dash.avgScore': 'Score moyen',
    'dash.recentActivity': 'Activité récente',
    'dash.noExams': 'Aucun examen passé',
    'dash.subscriberOnly': 'Réservé aux abonnés',
    'dash.startTrial': 'Commencer l\'essai',
    'dash.examLevel': 'Niveau d\'examen',
    'dash.startExam': 'Lancer l\'examen',
    'dash.categoryTraining': 'Entraînement par catégorie',
    'dash.chooseCat': 'Choisissez une catégorie pour un entraînement ciblé',
    'dash.subscriberEssential': 'Réservé aux abonnés Essential',
    'dash.upgradeEssential': 'Passer au Essential',
    'dash.videoGuides': 'Guides vidéo premium',
    'dash.examHistory': 'Historique des examens',
    'dash.newExam': 'Nouvel examen',
    'dash.noExamsYet': 'Aucun examen passé pour le moment',
    'dash.takeFirst': 'Passer votre premier examen',
    'dash.passed': 'Réussi',
    'dash.failed': 'Échoué',
    // About page
    'about.title': 'À propos de l\'Examen Civique',
    'about.subtitle': 'Informations officielles sur l\'examen de connaissance des valeurs de la République française.',
    'about.whatIs': 'Qu\'est-ce que l\'Examen Civique ?',
    'about.whatIsP1': 'L\'examen civique est un test de connaissance des valeurs et principes de la République française. Il a été instauré pour s\'assurer que les candidats à un titre de séjour ou à la nationalité française possèdent une compréhension suffisante des fondements de la République.',
    'about.whatIsP2': 'L\'examen est administré par l\'Office Français de l\'Immigration et de l\'Intégration (OFII) dans le cadre du parcours d\'intégration républicaine.',
    'about.whoMust': 'Qui doit passer cet examen ?',
    'about.cspTitle': 'CSP — Carte de Séjour Pluriannuelle',
    'about.cspDesc': 'Les étrangers souhaitant obtenir un titre de séjour pluriannuel après un premier titre d\'un an.',
    'about.crTitle': 'CR — Carte de Résident',
    'about.crDesc': 'Les candidats à la carte de résident de 10 ans, nécessitant une connaissance approfondie des institutions.',
    'about.natTitle': 'Naturalisation',
    'about.natDesc': 'Les candidats à la nationalité française, avec un niveau d\'exigence renforcé sur le patrimoine et l\'histoire.',
    'about.format': 'Format de l\'examen',
    'about.questions': 'Questions',
    'about.minutes': 'Minutes',
    'about.optionsPerQ': 'Options/question',
    'about.passThreshold': 'Seuil de réussite',
    'about.content': 'Contenu de l\'examen',
    'about.contentPrinciples': 'Principes de la République — Devise, laïcité, symboles',
    'about.contentInstitutions': 'Institutions — Démocratie, organisation, Europe',
    'about.contentRights': 'Droits et devoirs — Droits fondamentaux, devoirs civiques',
    'about.contentHistory': 'Histoire et géographie — Périodes clés, patrimoine',
    'about.contentLiving': 'Vie quotidienne — Santé, travail, éducation, résidence',
    'about.procedure': 'Déroulement et seuil de réussite',
    'about.procedureP1': 'L\'examen se déroule en 45 minutes. Le candidat doit répondre à 40 questions à choix multiples, chacune proposant 4 réponses dont une seule est correcte.',
    'about.procedureP2': 'Le seuil de réussite est fixé à 80%, soit un minimum de 32 bonnes réponses sur 40.',
    'about.procedureP3': '1 point est attribué par bonne réponse. Aucun point négatif n\'est appliqué pour les réponses incorrectes ou les questions sans réponse.',
    'about.resources': 'Ressources officielles',
    // Subscription gate
    'gate.classified': 'Classifié',
    'gate.tier1Title': 'Vous avez le potentiel pour réussir !',
    'gate.tier2Title': 'Débloquez les outils premium !',
    'gate.tier1Desc': 'Débloquez l\'accès illimité et le mode étude pour maximiser vos chances de réussite à l\'examen civique.',
    'gate.tier2Desc': 'Passez au Tier 2 pour accéder aux traductions, guides vidéo et outils avancés.',
    'gate.monthly': 'Mensuel',
    'gate.popular': 'Populaire',
    'gate.perMonth': '/mois',
    'gate.per6Months': '/6 mois',
    'gate.tier1Cta': 'Débloquer l\'accès — 6,99 €/mois',
    'gate.tier2Cta': 'Passer au Premium — 10,99 €/mois',
    'gate.later': 'Peut-être plus tard',
    'gate.feat1': 'Mode étude avec explications détaillées',
    'gate.feat2': 'Examens illimités sans répétition',
    'gate.feat3': 'Suivi de progression personnalisé',
    'gate.feat4': 'Entraînement par catégorie ciblé',
    'gate.feat5': 'Niveaux CR et Naturalisation',
    'gate.feat6': 'Traduction des questions en temps réel',
    'gate.feat7': 'Guides vidéo premium',
    'gate.feat8': 'Outils d\'étude avancés',
    'gate.feat9': 'Tous les avantages Standard inclus',
    // Learning keys
    'nav.learn': 'Apprendre',
    'nav.account': 'Compte',
    'hero.startLearning': 'Commencer à apprendre',
    'learn.welcome': 'Bienvenue, {name} !',
    'learn.subtitle': 'Que souhaitez-vous étudier aujourd\'hui ?',
    'learn.continueLearning': 'Continuer l\'apprentissage',
    'learn.learningPath': 'Mon parcours',
    'learn.practiceTest': 'Pratique & Tests',
    'learn.myProgress': 'Ma progression',
    'learn.demoExam': 'Examen démo',
    'learn.fullExam': 'Examen complet',
    'learn.training': 'Mode entraînement',
    'learn.categoryTraining': 'Entraînement par catégorie',
    'learn.lessonsCompleted': 'Leçons complétées',
    'learn.accuracy': 'Précision',
    'learn.examsTaken': 'Examens passés',
    'learn.weakAreas': 'Points faibles',
    'learn.resume': 'Reprendre',
    'learn.nextLesson': 'Leçon suivante',
    'learn.markComplete': 'Marquer comme terminé',
    'learn.practice': 'S\'entraîner',
    'learn.locked': 'Abonnement requis',
    'learn.upgrade': 'Passer au Standard',
    'learn.estimatedTime': 'Temps estimé',
    'learn.backToLearn': 'Retour au parcours',
    'learn.completed': 'Terminé',
    'learn.allCompleted': 'Toutes les leçons sont terminées !',
  },
  en: {
    'nav.home': 'Home',
    'nav.demo': 'Free Demo',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'hero.title': 'Prepare for your citizenship exam',
    'hero.subtitle': 'The official platform to pass your French civic exam in 2026',
    'hero.cta': 'Free Demo',
    'hero.cta2': 'View Pricing',
    'pricing.title': 'Simple and transparent pricing',
    'pricing.monthly': 'Monthly',
    'pricing.semester': '6 Months',
    'pricing.monthly.price': '€6.99',
    'pricing.semester.price': '€30.99',
    'pricing.feature1': 'Access all questions',
    'pricing.feature2': 'Exam and study modes',
    'pricing.feature3': 'Progress tracking',
    'pricing.feature4': 'Bilingual questions',
    'pricing.cta': 'Get Started',
    'pricing.save': 'Save 26%',
    'pricing.free': 'Free',
    'pricing.recommended': 'Recommended',
    'pricing.ctaFree': 'Create account',
    'pricing.ctaStandard': 'Choose Standard',
    'pricing.ctaPremium': 'Choose Premium',
    'pricing.feat.browse': 'Browse the site',
    'pricing.feat.demo': '1 demo exam',
    'pricing.feat.unlimited': 'Unlimited exams',
    'pricing.feat.training': 'Training mode',
    'pricing.feat.progress': 'Progress tracking',
    'pricing.feat.lessons': 'Access to lessons',
    'pricing.feat.path': 'Learning path',
    'pricing.feat.translation': 'Question translation',
    'pricing.feat.catTraining': 'Category training',
    'quiz.question': 'Question',
    'quiz.of': 'of',
    'quiz.next': 'Next',
    'quiz.prev': 'Previous',
    'quiz.finish': 'Finish',
    'quiz.timeRemaining': 'Time remaining',
    'quiz.study': 'Study Mode',
    'quiz.exam': 'Exam Mode',
    'quiz.explanation': 'Explanation',
    'quiz.correct': 'Correct!',
    'quiz.incorrect': 'Incorrect',
    'results.title': 'Exam Results',
    'results.passed': 'PASSED',
    'results.failed': 'FAILED',
    'results.score': 'Score',
    'results.time': 'Time',
    'results.categories': 'By Category',
    'results.retry': 'Try Again',
    'results.home': 'Back to Home',
    'results.passThreshold': 'Pass threshold: 80%',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.google': 'Continue with Google',
    'auth.or': 'or',
    'auth.noAccount': 'No account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.forgotPassword': 'Forgot password?',
    'auth.resetPassword': 'Reset password',
    'auth.resetSent': 'Email sent! Check your inbox.',
    'auth.backToLogin': 'Back to login',
    'footer.rights': '© 2026 GoCivique. All rights reserved.',
    'footer.disclaimer': 'This site is not affiliated with the French government. It is a private training platform for the Civic Exam.',
    'cat.Principles.desc': 'Liberty, Equality, Fraternity — Secularism, symbols and core values.',
    'cat.Institutions.desc': 'President, Parliament, Justice — the organization of the French State.',
    'cat.Rights.desc': 'Fundamental rights, civic duties and freedoms guaranteed by the Republic.',
    'cat.History.desc': 'Key periods, cultural heritage and geography of France.',
    'cat.Living.desc': 'Health, education, work — daily life in France.',
    'cat.Politics.desc': 'Political system, parties and civic participation.',
    'cat.Society.desc': 'Social cohesion, diversity and living together.',
    'cat.explore': 'Explore the Categories',
    'cat.exploreSubtitle': 'Prepare for each domain of the citizenship exam with targeted quizzes.',
    'cat.study': 'Practice',
    'progress.title': 'Track your progress',
    'progress.titleAuth': 'Your progress',
    'progress.subtitleGuest': 'Create an account to track your progress and statistics.',
    'progress.subtitleAuth': 'Based on your exam results',
    'progress.createAccount': 'Create an account',
    'progress.passProbability': 'Pass Probability',
    'progress.basedOnLast5': 'Based on the last 5 exams',
    'progress.examsTaken': 'Exams taken',
    'progress.avgScore': 'Average score',
    'progress.officialThreshold': 'Official threshold',
    'progress.bankProgress': 'Bank progress',
    'dash.dashboard': 'Dashboard',
    'dash.overallProgress': 'Overall progress',
    'dash.currentStatus': 'Current status',
    'dash.onTrack': 'On Track',
    'dash.needsPractice': 'Needs Practice',
    'dash.avgScore': 'Average score',
    'dash.recentActivity': 'Recent activity',
    'dash.noExams': 'No exams taken',
    'dash.subscriberOnly': 'Subscribers only',
    'dash.startTrial': 'Start Free Trial',
    'dash.examLevel': 'Exam level',
    'dash.startExam': 'Start exam',
    'dash.categoryTraining': 'Category training',
    'dash.chooseCat': 'Choose a category for targeted training',
    'dash.subscriberEssential': 'Essential subscribers only',
    'dash.upgradeEssential': 'Upgrade to Essential',
    'dash.videoGuides': 'Premium video guides',
    'dash.examHistory': 'Exam history',
    'dash.newExam': 'New exam',
    'dash.noExamsYet': 'No exams taken yet',
    'dash.takeFirst': 'Take your first exam',
    'dash.passed': 'Passed',
    'dash.failed': 'Failed',
    'about.title': 'About the Civic Exam',
    'about.subtitle': 'Official information about the French Republic values knowledge exam.',
    'about.whatIs': 'What is the Civic Exam?',
    'about.whatIsP1': 'The civic exam is a knowledge test on the values and principles of the French Republic. It was established to ensure that applicants for a residence permit or French nationality have a sufficient understanding of the Republic\'s foundations.',
    'about.whatIsP2': 'The exam is administered by the French Office for Immigration and Integration (OFII) as part of the republican integration process.',
    'about.whoMust': 'Who must take this exam?',
    'about.cspTitle': 'CSP — Multi-year Residence Permit',
    'about.cspDesc': 'Foreigners wishing to obtain a multi-year residence permit after an initial one-year permit.',
    'about.crTitle': 'CR — Resident Card',
    'about.crDesc': 'Applicants for the 10-year resident card, requiring in-depth knowledge of institutions.',
    'about.natTitle': 'Naturalization',
    'about.natDesc': 'Applicants for French nationality, with enhanced requirements on heritage and history.',
    'about.format': 'Exam format',
    'about.questions': 'Questions',
    'about.minutes': 'Minutes',
    'about.optionsPerQ': 'Options/question',
    'about.passThreshold': 'Pass threshold',
    'about.content': 'Exam content',
    'about.contentPrinciples': 'Principles of the Republic — Motto, secularism, symbols',
    'about.contentInstitutions': 'Institutions — Democracy, organization, Europe',
    'about.contentRights': 'Rights and duties — Fundamental rights, civic duties',
    'about.contentHistory': 'History and geography — Key periods, heritage',
    'about.contentLiving': 'Daily living — Health, work, education, residence',
    'about.procedure': 'Procedure and pass threshold',
    'about.procedureP1': 'The exam lasts 45 minutes. The candidate must answer 40 multiple-choice questions, each with 4 answers, only one being correct.',
    'about.procedureP2': 'The pass threshold is set at 80%, meaning a minimum of 32 correct answers out of 40.',
    'about.procedureP3': '1 point is awarded per correct answer. No negative points are applied for incorrect answers or unanswered questions.',
    'about.resources': 'Official resources',
    'gate.classified': 'Classified',
    'gate.tier1Title': 'You have the potential to succeed!',
    'gate.tier2Title': 'Unlock premium tools!',
    'gate.tier1Desc': 'Unlock unlimited access and study mode to maximize your chances of passing the civic exam.',
    'gate.tier2Desc': 'Upgrade to Tier 2 for translations, video guides and advanced tools.',
    'gate.monthly': 'Monthly',
    'gate.popular': 'Popular',
    'gate.perMonth': '/month',
    'gate.per6Months': '/6 months',
    'gate.tier1Cta': 'Unlock access — €6.99/month',
    'gate.tier2Cta': 'Upgrade to Premium — €10.99/month',
    'gate.later': 'Maybe later',
    'gate.feat1': 'Study mode with detailed explanations',
    'gate.feat2': 'Unlimited exams without repetition',
    'gate.feat3': 'Personalized progress tracking',
    'gate.feat4': 'Targeted category training',
    'gate.feat5': 'CR and Naturalization levels',
    'gate.feat6': 'Real-time question translation',
    'gate.feat7': 'Premium video guides',
    'gate.feat8': 'Advanced study tools',
    'gate.feat9': 'All Standard benefits included',
    'nav.learn': 'Learn',
    'nav.account': 'Account',
    'hero.startLearning': 'Start Learning',
    'learn.welcome': 'Welcome back, {name}!',
    'learn.subtitle': 'What would you like to study today?',
    'learn.continueLearning': 'Continue Learning',
    'learn.learningPath': 'My Learning Path',
    'learn.practiceTest': 'Practice & Test',
    'learn.myProgress': 'My Progress',
    'learn.demoExam': 'Demo Exam',
    'learn.fullExam': 'Full Exam',
    'learn.training': 'Training Mode',
    'learn.categoryTraining': 'Category Training',
    'learn.lessonsCompleted': 'Lessons Completed',
    'learn.accuracy': 'Accuracy',
    'learn.examsTaken': 'Exams Taken',
    'learn.weakAreas': 'Weak Areas',
    'learn.resume': 'Resume',
    'learn.nextLesson': 'Next Lesson',
    'learn.markComplete': 'Mark Complete',
    'learn.practice': 'Practice',
    'learn.locked': 'Subscription required',
    'learn.upgrade': 'Upgrade to Standard',
    'learn.estimatedTime': 'Estimated time',
    'learn.backToLearn': 'Back to learning',
    'learn.completed': 'Completed',
    'learn.allCompleted': 'All lessons completed!',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.demo': 'تجربة مجانية',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'nav.dashboard': 'لوحة التحكم',
    'nav.logout': 'تسجيل الخروج',
    'nav.pricing': 'الأسعار',
    'nav.about': 'حول الامتحان',
    'hero.title': 'استعد لامتحان الجنسية',
    'hero.subtitle': 'المنصة الرسمية لاجتياز امتحان المدنية الفرنسي في 2026',
    'hero.cta': 'تجربة مجانية',
    'hero.cta2': 'عرض الأسعار',
    'pricing.title': 'أسعار بسيطة وشفافة',
    'pricing.monthly': 'شهري',
    'pricing.semester': '6 أشهر',
    'pricing.monthly.price': '٦٫٩٩ €',
    'pricing.semester.price': '٣٠٫٩٩ €',
    'pricing.feature1': 'الوصول لجميع الأسئلة',
    'pricing.feature2': 'وضع الامتحان والدراسة',
    'pricing.feature3': 'تتبع التقدم',
    'pricing.feature4': 'أسئلة ثنائية اللغة',
    'pricing.cta': 'ابدأ الآن',
    'pricing.save': 'وفر 26%',
    'pricing.free': 'مجاني',
    'pricing.recommended': 'موصى به',
    'pricing.ctaFree': 'إنشاء حساب',
    'pricing.ctaStandard': 'اختر Standard',
    'pricing.ctaPremium': 'اختر Premium',
    'pricing.feat.browse': 'تصفح الموقع',
    'pricing.feat.demo': 'امتحان تجريبي واحد',
    'pricing.feat.unlimited': 'امتحانات غير محدودة',
    'pricing.feat.training': 'وضع التدريب',
    'pricing.feat.progress': 'تتبع التقدم',
    'pricing.feat.lessons': 'الوصول للدروس',
    'pricing.feat.path': 'مسار التعلم',
    'pricing.feat.translation': 'ترجمة الأسئلة',
    'pricing.feat.catTraining': 'تدريب حسب الفئة',
    'quiz.question': 'سؤال',
    'quiz.of': 'من',
    'quiz.next': 'التالي',
    'quiz.prev': 'السابق',
    'quiz.finish': 'إنهاء',
    'quiz.timeRemaining': 'الوقت المتبقي',
    'quiz.study': 'وضع الدراسة',
    'quiz.exam': 'وضع الامتحان',
    'quiz.explanation': 'التفسير',
    'quiz.correct': 'إجابة صحيحة!',
    'quiz.incorrect': 'إجابة خاطئة',
    'results.title': 'نتائج الامتحان',
    'results.passed': 'ناجح',
    'results.failed': 'راسب',
    'results.score': 'النتيجة',
    'results.time': 'الوقت',
    'results.categories': 'حسب الفئة',
    'results.retry': 'إعادة المحاولة',
    'results.home': 'العودة للرئيسية',
    'results.passThreshold': 'حد النجاح: 80%',
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.google': 'المتابعة مع جوجل',
    'auth.or': 'أو',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.resetPassword': 'إعادة تعيين كلمة المرور',
    'auth.resetSent': 'تم إرسال البريد! تحقق من صندوق الوارد.',
    'auth.backToLogin': 'العودة لتسجيل الدخول',
    'footer.rights': '© 2026 GoCivique. جميع الحقوق محفوظة.',
    'footer.disclaimer': 'هذا الموقع غير تابع للحكومة الفرنسية. إنه منصة تدريب خاصة للامتحان المدني.',
    'cat.Principles.desc': 'الحرية، المساواة، الأخوة — العلمانية، الرموز والقيم الأساسية.',
    'cat.Institutions.desc': 'الرئيس، البرلمان، القضاء — تنظيم الدولة الفرنسية.',
    'cat.Rights.desc': 'الحقوق الأساسية، الواجبات المدنية والحريات التي تكفلها الجمهورية.',
    'cat.History.desc': 'الفترات الرئيسية، التراث الثقافي وجغرافيا فرنسا.',
    'cat.Living.desc': 'الصحة، التعليم، العمل — الحياة اليومية في فرنسا.',
    'cat.Politics.desc': 'النظام السياسي والأحزاب والمشاركة المدنية.',
    'cat.Society.desc': 'التماسك الاجتماعي والتنوع والعيش المشترك.',
    'cat.explore': 'استكشف الفئات',
    'cat.exploreSubtitle': 'استعد لكل مجال من مجالات امتحان الجنسية مع اختبارات مستهدفة.',
    'cat.study': 'تدرب',
    'progress.title': 'تتبع تقدمك',
    'progress.titleAuth': 'تقدمك',
    'progress.subtitleGuest': 'أنشئ حسابًا لتتبع تقدمك وإحصائياتك.',
    'progress.subtitleAuth': 'بناءً على نتائج امتحاناتك',
    'progress.createAccount': 'إنشاء حساب',
    'progress.passProbability': 'احتمال النجاح',
    'progress.basedOnLast5': 'بناءً على آخر 5 امتحانات',
    'progress.examsTaken': 'الامتحانات المنجزة',
    'progress.avgScore': 'متوسط النتيجة',
    'progress.officialThreshold': 'الحد الرسمي',
    'progress.bankProgress': 'التقدم في البنك',
    'dash.dashboard': 'لوحة التحكم',
    'dash.overallProgress': 'التقدم العام',
    'dash.currentStatus': 'الحالة الحالية',
    'dash.onTrack': 'على المسار',
    'dash.needsPractice': 'يحتاج تدريب',
    'dash.avgScore': 'متوسط النتيجة',
    'dash.recentActivity': 'النشاط الأخير',
    'dash.noExams': 'لم يتم إجراء امتحانات',
    'dash.subscriberOnly': 'للمشتركين فقط',
    'dash.startTrial': 'بدء التجربة المجانية',
    'dash.examLevel': 'مستوى الامتحان',
    'dash.startExam': 'بدء الامتحان',
    'dash.categoryTraining': 'تدريب حسب الفئة',
    'dash.chooseCat': 'اختر فئة للتدريب المستهدف',
    'dash.subscriberEssential': 'للمشتركين Essential فقط',
    'dash.upgradeEssential': 'الترقية إلى Essential',
    'dash.videoGuides': 'أدلة فيديو متميزة',
    'dash.examHistory': 'سجل الامتحانات',
    'dash.newExam': 'امتحان جديد',
    'dash.noExamsYet': 'لم يتم إجراء أي امتحان حتى الآن',
    'dash.takeFirst': 'اجتياز أول امتحان',
    'dash.passed': 'ناجح',
    'dash.failed': 'راسب',
    'about.title': 'حول الامتحان المدني',
    'about.subtitle': 'معلومات رسمية حول امتحان معرفة قيم الجمهورية الفرنسية.',
    'about.whatIs': 'ما هو الامتحان المدني؟',
    'about.whatIsP1': 'الامتحان المدني هو اختبار معرفة بقيم ومبادئ الجمهورية الفرنسية. تم إنشاؤه للتأكد من أن المتقدمين للحصول على تصريح إقامة أو الجنسية الفرنسية لديهم فهم كافٍ لأسس الجمهورية.',
    'about.whatIsP2': 'يُدار الامتحان من قبل المكتب الفرنسي للهجرة والاندماج (OFII) في إطار مسار الاندماج الجمهوري.',
    'about.whoMust': 'من يجب أن يجتاز هذا الامتحان؟',
    'about.cspTitle': 'CSP — بطاقة إقامة متعددة السنوات',
    'about.cspDesc': 'الأجانب الراغبون في الحصول على تصريح إقامة متعدد السنوات بعد تصريح أولي لمدة عام.',
    'about.crTitle': 'CR — بطاقة مقيم',
    'about.crDesc': 'المتقدمون لبطاقة المقيم لمدة 10 سنوات، مع الحاجة لمعرفة معمقة بالمؤسسات.',
    'about.natTitle': 'التجنس',
    'about.natDesc': 'المتقدمون للجنسية الفرنسية، مع متطلبات معززة في التراث والتاريخ.',
    'about.format': 'شكل الامتحان',
    'about.questions': 'أسئلة',
    'about.minutes': 'دقائق',
    'about.optionsPerQ': 'خيارات/سؤال',
    'about.passThreshold': 'حد النجاح',
    'about.content': 'محتوى الامتحان',
    'about.contentPrinciples': 'مبادئ الجمهورية — الشعار، العلمانية، الرموز',
    'about.contentInstitutions': 'المؤسسات — الديمقراطية، التنظيم، أوروبا',
    'about.contentRights': 'الحقوق والواجبات — الحقوق الأساسية، الواجبات المدنية',
    'about.contentHistory': 'التاريخ والجغرافيا — الفترات الرئيسية، التراث',
    'about.contentLiving': 'الحياة اليومية — الصحة، العمل، التعليم، الإقامة',
    'about.procedure': 'الإجراء وحد النجاح',
    'about.procedureP1': 'يستغرق الامتحان 45 دقيقة. يجب على المرشح الإجابة على 40 سؤالاً متعدد الخيارات، كل منها يحتوي على 4 إجابات، واحدة منها فقط صحيحة.',
    'about.procedureP2': 'حد النجاح محدد بنسبة 80%، أي ما لا يقل عن 32 إجابة صحيحة من 40.',
    'about.procedureP3': 'يُمنح نقطة واحدة لكل إجابة صحيحة. لا تُطبق نقاط سلبية على الإجابات الخاطئة أو الأسئلة بدون إجابة.',
    'about.resources': 'موارد رسمية',
    'gate.classified': 'سري',
    'gate.tier1Title': 'لديك القدرة على النجاح!',
    'gate.tier2Title': 'افتح الأدوات المتميزة!',
    'gate.tier1Desc': 'افتح الوصول غير المحدود ووضع الدراسة لتعظيم فرصك في اجتياز الامتحان المدني.',
    'gate.tier2Desc': 'قم بالترقية إلى المستوى 2 للترجمات وأدلة الفيديو والأدوات المتقدمة.',
    'gate.monthly': 'شهري',
    'gate.popular': 'شائع',
    'gate.perMonth': '/شهر',
    'gate.per6Months': '/6 أشهر',
    'gate.tier1Cta': 'فتح الوصول — ٦٫٩٩ €/شهر',
    'gate.tier2Cta': 'الترقية إلى Premium — ١٠٫٩٩ €/شهر',
    'gate.later': 'ربما لاحقًا',
    'gate.feat1': 'وضع دراسة مع شروحات مفصلة',
    'gate.feat2': 'امتحانات غير محدودة بدون تكرار',
    'gate.feat3': 'تتبع تقدم مخصص',
    'gate.feat4': 'تدريب مستهدف حسب الفئة',
    'gate.feat5': 'مستويات CR والتجنس',
    'gate.feat6': 'ترجمة فورية للأسئلة',
    'gate.feat7': 'أدلة فيديو متميزة',
    'gate.feat8': 'أدوات دراسة متقدمة',
    'gate.feat9': 'جميع مزايا Standard مشمولة',
    'nav.learn': 'تعلم',
    'nav.account': 'الحساب',
    'hero.startLearning': 'ابدأ التعلم',
    'learn.welcome': 'مرحبًا، {name}!',
    'learn.subtitle': 'ماذا تريد أن تدرس اليوم؟',
    'learn.continueLearning': 'تابع التعلم',
    'learn.learningPath': 'مسار التعلم',
    'learn.practiceTest': 'تمارين واختبارات',
    'learn.myProgress': 'تقدمي',
    'learn.demoExam': 'امتحان تجريبي',
    'learn.fullExam': 'امتحان كامل',
    'learn.training': 'وضع التدريب',
    'learn.categoryTraining': 'تدريب حسب الفئة',
    'learn.lessonsCompleted': 'الدروس المكتملة',
    'learn.accuracy': 'الدقة',
    'learn.examsTaken': 'الامتحانات المنجزة',
    'learn.weakAreas': 'نقاط الضعف',
    'learn.resume': 'استئناف',
    'learn.nextLesson': 'الدرس التالي',
    'learn.markComplete': 'وضع علامة مكتمل',
    'learn.practice': 'تمرين',
    'learn.locked': 'يتطلب اشتراك',
    'learn.upgrade': 'الترقية إلى Standard',
    'learn.estimatedTime': 'الوقت المقدر',
    'learn.backToLearn': 'العودة للتعلم',
    'learn.completed': 'مكتمل',
    'learn.allCompleted': 'تم إكمال جميع الدروس!',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.demo': 'Demo gratis',
    'nav.login': 'Iniciar sesión',
    'nav.signup': 'Registrarse',
    'nav.dashboard': 'Panel',
    'nav.logout': 'Cerrar sesión',
    'nav.pricing': 'Precios',
    'nav.about': 'Sobre el examen',
    'hero.title': 'Prepara tu examen de ciudadanía',
    'hero.subtitle': 'La plataforma oficial para aprobar tu examen cívico francés en 2026',
    'hero.cta': 'Demo gratis',
    'hero.cta2': 'Ver precios',
    'pricing.title': 'Precios simples y transparentes',
    'pricing.monthly': 'Mensual',
    'pricing.semester': '6 Meses',
    'pricing.monthly.price': '6,99 €',
    'pricing.semester.price': '30,99 €',
    'pricing.feature1': 'Acceso a todas las preguntas',
    'pricing.feature2': 'Modo examen y estudio',
    'pricing.feature3': 'Seguimiento del progreso',
    'pricing.feature4': 'Preguntas bilingües',
    'pricing.cta': 'Empezar',
    'pricing.save': 'Ahorra 26%',
    'pricing.free': 'Gratis',
    'pricing.recommended': 'Recomendado',
    'pricing.ctaFree': 'Crear cuenta',
    'pricing.ctaStandard': 'Elegir Standard',
    'pricing.ctaPremium': 'Elegir Premium',
    'pricing.feat.browse': 'Navegar por el sitio',
    'pricing.feat.demo': '1 examen demo',
    'pricing.feat.unlimited': 'Exámenes ilimitados',
    'pricing.feat.training': 'Modo entrenamiento',
    'pricing.feat.progress': 'Seguimiento del progreso',
    'pricing.feat.lessons': 'Acceso a lecciones',
    'pricing.feat.path': 'Ruta de aprendizaje',
    'pricing.feat.translation': 'Traducción de preguntas',
    'pricing.feat.catTraining': 'Entrenamiento por categoría',
    'quiz.question': 'Pregunta',
    'quiz.of': 'de',
    'quiz.next': 'Siguiente',
    'quiz.prev': 'Anterior',
    'quiz.finish': 'Terminar',
    'quiz.timeRemaining': 'Tiempo restante',
    'quiz.study': 'Modo estudio',
    'quiz.exam': 'Modo examen',
    'quiz.explanation': 'Explicación',
    'quiz.correct': '¡Correcto!',
    'quiz.incorrect': 'Incorrecto',
    'results.title': 'Resultados del examen',
    'results.passed': 'APROBADO',
    'results.failed': 'SUSPENDIDO',
    'results.score': 'Puntuación',
    'results.time': 'Tiempo',
    'results.categories': 'Por categoría',
    'results.retry': 'Reintentar',
    'results.home': 'Volver al inicio',
    'results.passThreshold': 'Umbral de aprobación: 80%',
    'auth.login': 'Iniciar sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.google': 'Continuar con Google',
    'auth.or': 'o',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.resetPassword': 'Restablecer contraseña',
    'auth.resetSent': '¡Email enviado! Revisa tu bandeja de entrada.',
    'auth.backToLogin': 'Volver al inicio de sesión',
    'footer.rights': '© 2026 GoCivique. Todos los derechos reservados.',
    'footer.disclaimer': 'Este sitio no está afiliado al gobierno francés. Es una plataforma de entrenamiento privada para el Examen Cívico.',
    'cat.Principles.desc': 'Libertad, Igualdad, Fraternidad — Laicidad, símbolos y valores fundamentales.',
    'cat.Institutions.desc': 'Presidente, Parlamento, Justicia — la organización del Estado francés.',
    'cat.Rights.desc': 'Derechos fundamentales, deberes cívicos y libertades garantizadas por la República.',
    'cat.History.desc': 'Períodos clave, patrimonio cultural y geografía de Francia.',
    'cat.Living.desc': 'Salud, educación, trabajo — la vida cotidiana en Francia.',
    'cat.Politics.desc': 'Sistema político, partidos y participación ciudadana.',
    'cat.Society.desc': 'Cohesión social, diversidad y convivencia.',
    'cat.explore': 'Explora las categorías',
    'cat.exploreSubtitle': 'Prepara cada área del examen de ciudadanía con cuestionarios específicos.',
    'cat.study': 'Practicar',
    'progress.title': 'Sigue tu progreso',
    'progress.titleAuth': 'Tu progreso',
    'progress.subtitleGuest': 'Crea una cuenta para seguir tu progreso y estadísticas.',
    'progress.subtitleAuth': 'Basado en tus resultados de exámenes',
    'progress.createAccount': 'Crear una cuenta',
    'progress.passProbability': 'Probabilidad de aprobación',
    'progress.basedOnLast5': 'Basada en los últimos 5 exámenes',
    'progress.examsTaken': 'Exámenes realizados',
    'progress.avgScore': 'Puntuación media',
    'progress.officialThreshold': 'Umbral oficial',
    'progress.bankProgress': 'Progreso en el banco',
    'dash.dashboard': 'Panel',
    'dash.overallProgress': 'Progreso general',
    'dash.currentStatus': 'Estado actual',
    'dash.onTrack': 'En camino',
    'dash.needsPractice': 'Necesita práctica',
    'dash.avgScore': 'Puntuación media',
    'dash.recentActivity': 'Actividad reciente',
    'dash.noExams': 'Sin exámenes realizados',
    'dash.subscriberOnly': 'Solo suscriptores',
    'dash.startTrial': 'Iniciar prueba gratuita',
    'dash.examLevel': 'Nivel de examen',
    'dash.startExam': 'Iniciar examen',
    'dash.categoryTraining': 'Entrenamiento por categoría',
    'dash.chooseCat': 'Elige una categoría para un entrenamiento específico',
    'dash.subscriberEssential': 'Solo suscriptores Essential',
    'dash.upgradeEssential': 'Pasar a Essential',
    'dash.videoGuides': 'Guías de vídeo premium',
    'dash.examHistory': 'Historial de exámenes',
    'dash.newExam': 'Nuevo examen',
    'dash.noExamsYet': 'Ningún examen realizado todavía',
    'dash.takeFirst': 'Realiza tu primer examen',
    'dash.passed': 'Aprobado',
    'dash.failed': 'Suspendido',
    'about.title': 'Sobre el Examen Cívico',
    'about.subtitle': 'Información oficial sobre el examen de conocimiento de los valores de la República Francesa.',
    'about.whatIs': '¿Qué es el Examen Cívico?',
    'about.whatIsP1': 'El examen cívico es una prueba de conocimiento sobre los valores y principios de la República Francesa. Fue establecido para asegurar que los solicitantes de un permiso de residencia o la nacionalidad francesa tienen una comprensión suficiente de los fundamentos de la República.',
    'about.whatIsP2': 'El examen es administrado por la Oficina Francesa de Inmigración e Integración (OFII) como parte del proceso de integración republicana.',
    'about.whoMust': '¿Quién debe realizar este examen?',
    'about.cspTitle': 'CSP — Permiso de residencia plurianual',
    'about.cspDesc': 'Extranjeros que desean obtener un permiso de residencia plurianual tras un primer permiso de un año.',
    'about.crTitle': 'CR — Tarjeta de residente',
    'about.crDesc': 'Solicitantes de la tarjeta de residente de 10 años, que requiere un conocimiento profundo de las instituciones.',
    'about.natTitle': 'Naturalización',
    'about.natDesc': 'Solicitantes de la nacionalidad francesa, con requisitos reforzados sobre patrimonio e historia.',
    'about.format': 'Formato del examen',
    'about.questions': 'Preguntas',
    'about.minutes': 'Minutos',
    'about.optionsPerQ': 'Opciones/pregunta',
    'about.passThreshold': 'Umbral de aprobación',
    'about.content': 'Contenido del examen',
    'about.contentPrinciples': 'Principios de la República — Lema, laicidad, símbolos',
    'about.contentInstitutions': 'Instituciones — Democracia, organización, Europa',
    'about.contentRights': 'Derechos y deberes — Derechos fundamentales, deberes cívicos',
    'about.contentHistory': 'Historia y geografía — Períodos clave, patrimonio',
    'about.contentLiving': 'Vida cotidiana — Salud, trabajo, educación, residencia',
    'about.procedure': 'Procedimiento y umbral de aprobación',
    'about.procedureP1': 'El examen dura 45 minutos. El candidato debe responder a 40 preguntas de opción múltiple, cada una con 4 respuestas, siendo solo una correcta.',
    'about.procedureP2': 'El umbral de aprobación se fija en el 80%, es decir, un mínimo de 32 respuestas correctas de 40.',
    'about.procedureP3': 'Se otorga 1 punto por respuesta correcta. No se aplican puntos negativos por respuestas incorrectas o preguntas sin respuesta.',
    'about.resources': 'Recursos oficiales',
    'gate.classified': 'Clasificado',
    'gate.tier1Title': '¡Tienes el potencial para aprobar!',
    'gate.tier2Title': '¡Desbloquea herramientas premium!',
    'gate.tier1Desc': 'Desbloquea acceso ilimitado y modo estudio para maximizar tus posibilidades de aprobar el examen cívico.',
    'gate.tier2Desc': 'Pasa al Tier 2 para acceder a traducciones, guías de vídeo y herramientas avanzadas.',
    'gate.monthly': 'Mensual',
    'gate.popular': 'Popular',
    'gate.perMonth': '/mes',
    'gate.per6Months': '/6 meses',
    'gate.tier1Cta': 'Desbloquear acceso — 6,99 €/mes',
    'gate.tier2Cta': 'Pasar a Premium — 10,99 €/mes',
    'gate.later': 'Quizás más tarde',
    'gate.feat1': 'Modo estudio con explicaciones detalladas',
    'gate.feat2': 'Exámenes ilimitados sin repetición',
    'gate.feat3': 'Seguimiento de progreso personalizado',
    'gate.feat4': 'Entrenamiento por categoría específico',
    'gate.feat5': 'Niveles CR y Naturalización',
    'gate.feat6': 'Traducción de preguntas en tiempo real',
    'gate.feat7': 'Guías de vídeo premium',
    'gate.feat8': 'Herramientas de estudio avanzadas',
    'gate.feat9': 'Todos los beneficios Standard incluidos',
    'nav.learn': 'Aprender',
    'nav.account': 'Cuenta',
    'hero.startLearning': 'Empezar a aprender',
    'learn.welcome': '¡Bienvenido, {name}!',
    'learn.subtitle': '¿Qué te gustaría estudiar hoy?',
    'learn.continueLearning': 'Continuar aprendiendo',
    'learn.learningPath': 'Mi ruta de aprendizaje',
    'learn.practiceTest': 'Práctica y Tests',
    'learn.myProgress': 'Mi progreso',
    'learn.demoExam': 'Examen demo',
    'learn.fullExam': 'Examen completo',
    'learn.training': 'Modo entrenamiento',
    'learn.categoryTraining': 'Entrenamiento por categoría',
    'learn.lessonsCompleted': 'Lecciones completadas',
    'learn.accuracy': 'Precisión',
    'learn.examsTaken': 'Exámenes realizados',
    'learn.weakAreas': 'Áreas débiles',
    'learn.resume': 'Continuar',
    'learn.nextLesson': 'Siguiente lección',
    'learn.markComplete': 'Marcar como completado',
    'learn.practice': 'Practicar',
    'learn.locked': 'Suscripción requerida',
    'learn.upgrade': 'Pasar a Standard',
    'learn.estimatedTime': 'Tiempo estimado',
    'learn.backToLearn': 'Volver al aprendizaje',
    'learn.completed': 'Completado',
    'learn.allCompleted': '¡Todas las lecciones completadas!',
  },
  pt: {
    'nav.home': 'Início',
    'nav.demo': 'Demo grátis',
    'nav.login': 'Entrar',
    'nav.signup': 'Registar',
    'nav.dashboard': 'Painel',
    'nav.logout': 'Sair',
    'nav.pricing': 'Preços',
    'nav.about': 'Sobre o exame',
    'hero.title': 'Prepare o seu exame de cidadania',
    'hero.subtitle': 'A plataforma oficial para passar no exame cívico francês em 2026',
    'hero.cta': 'Demo grátis',
    'hero.cta2': 'Ver preços',
    'pricing.title': 'Preços simples e transparentes',
    'pricing.monthly': 'Mensal',
    'pricing.semester': '6 Meses',
    'pricing.monthly.price': '6,99 €',
    'pricing.semester.price': '30,99 €',
    'pricing.feature1': 'Acesso a todas as questões',
    'pricing.feature2': 'Modo exame e estudo',
    'pricing.feature3': 'Acompanhamento do progresso',
    'pricing.feature4': 'Questões bilíngues',
    'pricing.cta': 'Começar',
    'pricing.save': 'Poupe 26%',
    'pricing.free': 'Grátis',
    'pricing.recommended': 'Recomendado',
    'pricing.ctaFree': 'Criar conta',
    'pricing.ctaStandard': 'Escolher Standard',
    'pricing.ctaPremium': 'Escolher Premium',
    'pricing.feat.browse': 'Navegar no site',
    'pricing.feat.demo': '1 exame demo',
    'pricing.feat.unlimited': 'Exames ilimitados',
    'pricing.feat.training': 'Modo treino',
    'pricing.feat.progress': 'Acompanhamento do progresso',
    'pricing.feat.lessons': 'Acesso às lições',
    'pricing.feat.path': 'Percurso de aprendizagem',
    'pricing.feat.translation': 'Tradução de questões',
    'pricing.feat.catTraining': 'Treino por categoria',
    'quiz.question': 'Questão',
    'quiz.of': 'de',
    'quiz.next': 'Seguinte',
    'quiz.prev': 'Anterior',
    'quiz.finish': 'Terminar',
    'quiz.timeRemaining': 'Tempo restante',
    'quiz.study': 'Modo estudo',
    'quiz.exam': 'Modo exame',
    'quiz.explanation': 'Explicação',
    'quiz.correct': 'Correto!',
    'quiz.incorrect': 'Incorreto',
    'results.title': 'Resultados do exame',
    'results.passed': 'APROVADO',
    'results.failed': 'REPROVADO',
    'results.score': 'Pontuação',
    'results.time': 'Tempo',
    'results.categories': 'Por categoria',
    'results.retry': 'Tentar novamente',
    'results.home': 'Voltar ao início',
    'results.passThreshold': 'Limiar de aprovação: 80%',
    'auth.login': 'Entrar',
    'auth.signup': 'Registar',
    'auth.email': 'Email',
    'auth.password': 'Palavra-passe',
    'auth.google': 'Continuar com Google',
    'auth.or': 'ou',
    'auth.noAccount': 'Não tem conta?',
    'auth.hasAccount': 'Já tem conta?',
    'auth.forgotPassword': 'Esqueceu a palavra-passe?',
    'auth.resetPassword': 'Redefinir palavra-passe',
    'auth.resetSent': 'Email enviado! Verifique a sua caixa de entrada.',
    'auth.backToLogin': 'Voltar ao login',
    'footer.rights': '© 2026 GoCivique. Todos os direitos reservados.',
    'footer.disclaimer': 'Este site não é afiliado ao governo francês. É uma plataforma de treino privada para o Exame Cívico.',
    'cat.Principles.desc': 'Liberdade, Igualdade, Fraternidade — Laicidade, símbolos e valores fundamentais.',
    'cat.Institutions.desc': 'Presidente, Parlamento, Justiça — a organização do Estado francês.',
    'cat.Rights.desc': 'Direitos fundamentais, deveres cívicos e liberdades garantidas pela República.',
    'cat.History.desc': 'Períodos-chave, património cultural e geografia da França.',
    'cat.Living.desc': 'Saúde, educação, trabalho — a vida quotidiana em França.',
    'cat.Politics.desc': 'Sistema político, partidos e participação cívica.',
    'cat.Society.desc': 'Coesão social, diversidade e convivência.',
    'cat.explore': 'Explore as categorias',
    'cat.exploreSubtitle': 'Prepare cada área do exame de cidadania com questionários direcionados.',
    'cat.study': 'Praticar',
    'progress.title': 'Acompanhe o seu progresso',
    'progress.titleAuth': 'O seu progresso',
    'progress.subtitleGuest': 'Crie uma conta para acompanhar o seu progresso e estatísticas.',
    'progress.subtitleAuth': 'Baseado nos seus resultados de exames',
    'progress.createAccount': 'Criar uma conta',
    'progress.passProbability': 'Probabilidade de aprovação',
    'progress.basedOnLast5': 'Baseada nos últimos 5 exames',
    'progress.examsTaken': 'Exames realizados',
    'progress.avgScore': 'Pontuação média',
    'progress.officialThreshold': 'Limiar oficial',
    'progress.bankProgress': 'Progresso no banco',
    'dash.dashboard': 'Painel',
    'dash.overallProgress': 'Progresso geral',
    'dash.currentStatus': 'Estado atual',
    'dash.onTrack': 'No caminho certo',
    'dash.needsPractice': 'Precisa de prática',
    'dash.avgScore': 'Pontuação média',
    'dash.recentActivity': 'Atividade recente',
    'dash.noExams': 'Nenhum exame realizado',
    'dash.subscriberOnly': 'Apenas para assinantes',
    'dash.startTrial': 'Iniciar teste gratuito',
    'dash.examLevel': 'Nível do exame',
    'dash.startExam': 'Iniciar exame',
    'dash.categoryTraining': 'Treino por categoria',
    'dash.chooseCat': 'Escolha uma categoria para treino direcionado',
    'dash.subscriberEssential': 'Apenas assinantes Essential',
    'dash.upgradeEssential': 'Passar para Essential',
    'dash.videoGuides': 'Guias de vídeo premium',
    'dash.examHistory': 'Histórico de exames',
    'dash.newExam': 'Novo exame',
    'dash.noExamsYet': 'Nenhum exame realizado ainda',
    'dash.takeFirst': 'Realize o seu primeiro exame',
    'dash.passed': 'Aprovado',
    'dash.failed': 'Reprovado',
    'about.title': 'Sobre o Exame Cívico',
    'about.subtitle': 'Informações oficiais sobre o exame de conhecimento dos valores da República Francesa.',
    'about.whatIs': 'O que é o Exame Cívico?',
    'about.whatIsP1': 'O exame cívico é um teste de conhecimento sobre os valores e princípios da República Francesa. Foi criado para garantir que os candidatos a uma autorização de residência ou à nacionalidade francesa possuem uma compreensão suficiente dos fundamentos da República.',
    'about.whatIsP2': 'O exame é administrado pelo Escritório Francês de Imigração e Integração (OFII) no âmbito do percurso de integração republicana.',
    'about.whoMust': 'Quem deve fazer este exame?',
    'about.cspTitle': 'CSP — Autorização de residência plurianual',
    'about.cspDesc': 'Estrangeiros que desejam obter uma autorização de residência plurianual após uma autorização inicial de um ano.',
    'about.crTitle': 'CR — Cartão de residente',
    'about.crDesc': 'Candidatos ao cartão de residente de 10 anos, exigindo conhecimento aprofundado das instituições.',
    'about.natTitle': 'Naturalização',
    'about.natDesc': 'Candidatos à nacionalidade francesa, com requisitos reforçados sobre património e história.',
    'about.format': 'Formato do exame',
    'about.questions': 'Questões',
    'about.minutes': 'Minutos',
    'about.optionsPerQ': 'Opções/questão',
    'about.passThreshold': 'Limiar de aprovação',
    'about.content': 'Conteúdo do exame',
    'about.contentPrinciples': 'Princípios da República — Lema, laicidade, símbolos',
    'about.contentInstitutions': 'Instituições — Democracia, organização, Europa',
    'about.contentRights': 'Direitos e deveres — Direitos fundamentais, deveres cívicos',
    'about.contentHistory': 'História e geografia — Períodos-chave, património',
    'about.contentLiving': 'Vida quotidiana — Saúde, trabalho, educação, residência',
    'about.procedure': 'Procedimento e limiar de aprovação',
    'about.procedureP1': 'O exame tem a duração de 45 minutos. O candidato deve responder a 40 questões de escolha múltipla, cada uma com 4 respostas, sendo apenas uma correta.',
    'about.procedureP2': 'O limiar de aprovação é fixado em 80%, ou seja, um mínimo de 32 respostas corretas em 40.',
    'about.procedureP3': 'É atribuído 1 ponto por resposta correta. Não são aplicados pontos negativos por respostas incorretas ou questões sem resposta.',
    'about.resources': 'Recursos oficiais',
    'gate.classified': 'Classificado',
    'gate.tier1Title': 'Tem o potencial para passar!',
    'gate.tier2Title': 'Desbloqueie ferramentas premium!',
    'gate.tier1Desc': 'Desbloqueie acesso ilimitado e modo estudo para maximizar as suas hipóteses de passar no exame cívico.',
    'gate.tier2Desc': 'Passe para o Tier 2 para aceder a traduções, guias de vídeo e ferramentas avançadas.',
    'gate.monthly': 'Mensal',
    'gate.popular': 'Popular',
    'gate.perMonth': '/mês',
    'gate.per6Months': '/6 meses',
    'gate.tier1Cta': 'Desbloquear acesso — 6,99 €/mês',
    'gate.tier2Cta': 'Passar para Premium — 10,99 €/mês',
    'gate.later': 'Talvez mais tarde',
    'gate.feat1': 'Modo estudo com explicações detalhadas',
    'gate.feat2': 'Exames ilimitados sem repetição',
    'gate.feat3': 'Acompanhamento de progresso personalizado',
    'gate.feat4': 'Treino por categoria direcionado',
    'gate.feat5': 'Níveis CR e Naturalização',
    'gate.feat6': 'Tradução de questões em tempo real',
    'gate.feat7': 'Guias de vídeo premium',
    'gate.feat8': 'Ferramentas de estudo avançadas',
    'gate.feat9': 'Todos os benefícios Standard incluídos',
    'nav.learn': 'Aprender',
    'nav.account': 'Conta',
    'hero.startLearning': 'Começar a aprender',
    'learn.welcome': 'Bem-vindo, {name}!',
    'learn.subtitle': 'O que gostaria de estudar hoje?',
    'learn.continueLearning': 'Continuar a aprender',
    'learn.learningPath': 'O meu percurso',
    'learn.practiceTest': 'Prática e Testes',
    'learn.myProgress': 'O meu progresso',
    'learn.demoExam': 'Exame demo',
    'learn.fullExam': 'Exame completo',
    'learn.training': 'Modo treino',
    'learn.categoryTraining': 'Treino por categoria',
    'learn.lessonsCompleted': 'Lições concluídas',
    'learn.accuracy': 'Precisão',
    'learn.examsTaken': 'Exames realizados',
    'learn.weakAreas': 'Áreas fracas',
    'learn.resume': 'Retomar',
    'learn.nextLesson': 'Próxima lição',
    'learn.markComplete': 'Marcar como concluído',
    'learn.practice': 'Praticar',
    'learn.locked': 'Subscrição necessária',
    'learn.upgrade': 'Passar para Standard',
    'learn.estimatedTime': 'Tempo estimado',
    'learn.backToLearn': 'Voltar ao aprendizagem',
    'learn.completed': 'Concluído',
    'learn.allCompleted': 'Todas as lições concluídas!',
  },
  zh: {
    'nav.home': '首页',
    'nav.demo': '免费试用',
    'nav.login': '登录',
    'nav.signup': '注册',
    'nav.dashboard': '仪表板',
    'nav.logout': '退出',
    'nav.pricing': '价格',
    'nav.about': '关于考试',
    'hero.title': '准备您的公民考试',
    'hero.subtitle': '2026年通过法国公民考试的官方平台',
    'hero.cta': '免费试用',
    'hero.cta2': '查看价格',
    'pricing.title': '简单透明的定价',
    'pricing.monthly': '每月',
    'pricing.semester': '6个月',
    'pricing.monthly.price': '€6.99',
    'pricing.semester.price': '€30.99',
    'pricing.feature1': '访问所有题目',
    'pricing.feature2': '考试和学习模式',
    'pricing.feature3': '进度跟踪',
    'pricing.feature4': '双语题目',
    'pricing.cta': '开始',
    'pricing.save': '节省26%',
    'pricing.free': '免费',
    'pricing.recommended': '推荐',
    'pricing.ctaFree': '创建账户',
    'pricing.ctaStandard': '选择Standard',
    'pricing.ctaPremium': '选择Premium',
    'pricing.feat.browse': '浏览网站',
    'pricing.feat.demo': '1次演示考试',
    'pricing.feat.unlimited': '无限考试',
    'pricing.feat.training': '训练模式',
    'pricing.feat.progress': '进度跟踪',
    'pricing.feat.lessons': '访问课程',
    'pricing.feat.path': '学习路径',
    'pricing.feat.translation': '题目翻译',
    'pricing.feat.catTraining': '分类训练',
    'quiz.question': '问题',
    'quiz.of': '/',
    'quiz.next': '下一题',
    'quiz.prev': '上一题',
    'quiz.finish': '完成',
    'quiz.timeRemaining': '剩余时间',
    'quiz.study': '学习模式',
    'quiz.exam': '考试模式',
    'quiz.explanation': '解释',
    'quiz.correct': '正确！',
    'quiz.incorrect': '错误',
    'results.title': '考试结果',
    'results.passed': '通过',
    'results.failed': '未通过',
    'results.score': '分数',
    'results.time': '时间',
    'results.categories': '按类别',
    'results.retry': '重试',
    'results.home': '返回首页',
    'results.passThreshold': '及格线：80%',
    'auth.login': '登录',
    'auth.signup': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.google': '使用Google继续',
    'auth.or': '或',
    'auth.noAccount': '没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.forgotPassword': '忘记密码？',
    'auth.resetPassword': '重置密码',
    'auth.resetSent': '邮件已发送！请查看收件箱。',
    'auth.backToLogin': '返回登录',
    'footer.rights': '© 2026 GoCivique. 保留所有权利。',
    'footer.disclaimer': '本网站与法国政府无关。这是一个私人公民考试培训平台。',
    'cat.Principles.desc': '自由、平等、博爱 — 政教分离、象征和核心价值观。',
    'cat.Institutions.desc': '总统、议会、司法 — 法国国家组织。',
    'cat.Rights.desc': '基本权利、公民义务和共和国保障的自由。',
    'cat.History.desc': '关键时期、文化遗产和法国地理。',
    'cat.Living.desc': '健康、教育、工作 — 法国的日常生活。',
    'cat.Politics.desc': '政治制度、政党和公民参与。',
    'cat.Society.desc': '社会凝聚力、多样性和共同生活。',
    'cat.explore': '探索类别',
    'cat.exploreSubtitle': '通过有针对性的测验准备公民考试的每个领域。',
    'cat.study': '练习',
    'progress.title': '跟踪您的进度',
    'progress.titleAuth': '您的进度',
    'progress.subtitleGuest': '创建账户以跟踪您的进度和统计数据。',
    'progress.subtitleAuth': '基于您的考试结果',
    'progress.createAccount': '创建账户',
    'progress.passProbability': '通过概率',
    'progress.basedOnLast5': '基于最近5次考试',
    'progress.examsTaken': '已参加考试',
    'progress.avgScore': '平均分数',
    'progress.officialThreshold': '官方线',
    'progress.bankProgress': '题库进度',
    'dash.dashboard': '仪表板',
    'dash.overallProgress': '整体进度',
    'dash.currentStatus': '当前状态',
    'dash.onTrack': '进展良好',
    'dash.needsPractice': '需要练习',
    'dash.avgScore': '平均分数',
    'dash.recentActivity': '最近活动',
    'dash.noExams': '未参加考试',
    'dash.subscriberOnly': '仅限订阅者',
    'dash.startTrial': '开始免费试用',
    'dash.examLevel': '考试级别',
    'dash.startExam': '开始考试',
    'dash.categoryTraining': '分类训练',
    'dash.chooseCat': '选择一个类别进行有针对性的训练',
    'dash.subscriberEssential': '仅限Essential订阅者',
    'dash.upgradeEssential': '升级到Essential',
    'dash.videoGuides': '高级视频指南',
    'dash.examHistory': '考试历史',
    'dash.newExam': '新考试',
    'dash.noExamsYet': '尚未参加任何考试',
    'dash.takeFirst': '参加您的第一次考试',
    'dash.passed': '通过',
    'dash.failed': '未通过',
    'about.title': '关于公民考试',
    'about.subtitle': '关于法兰西共和国价值观知识考试的官方信息。',
    'about.whatIs': '什么是公民考试？',
    'about.whatIsP1': '公民考试是关于法兰西共和国价值观和原则的知识测试。它的设立是为了确保申请居留许可或法国国籍的候选人对共和国的基础有足够的了解。',
    'about.whatIsP2': '该考试由法国移民和融合办公室(OFII)在共和融合过程中管理。',
    'about.whoMust': '谁需要参加这个考试？',
    'about.cspTitle': 'CSP — 多年期居留许可',
    'about.cspDesc': '希望在首个一年期许可后获得多年期居留许可的外国人。',
    'about.crTitle': 'CR — 居民卡',
    'about.crDesc': '10年居民卡的申请人，需要对机构有深入了解。',
    'about.natTitle': '入籍',
    'about.natDesc': '法国国籍申请人，对遗产和历史有更高要求。',
    'about.format': '考试形式',
    'about.questions': '题目',
    'about.minutes': '分钟',
    'about.optionsPerQ': '选项/题',
    'about.passThreshold': '及格线',
    'about.content': '考试内容',
    'about.contentPrinciples': '共和国原则 — 格言、政教分离、象征',
    'about.contentInstitutions': '机构 — 民主、组织、欧洲',
    'about.contentRights': '权利与义务 — 基本权利、公民义务',
    'about.contentHistory': '历史与地理 — 关键时期、遗产',
    'about.contentLiving': '日常生活 — 健康、工作、教育、居住',
    'about.procedure': '流程和及格线',
    'about.procedureP1': '考试时长45分钟。考生必须回答40道选择题，每题有4个选项，只有一个正确。',
    'about.procedureP2': '及格线设定为80%，即40题中至少答对32题。',
    'about.procedureP3': '每个正确答案得1分。错误答案或未作答的题目不扣分。',
    'about.resources': '官方资源',
    'gate.classified': '机密',
    'gate.tier1Title': '您有通过的潜力！',
    'gate.tier2Title': '解锁高级工具！',
    'gate.tier1Desc': '解锁无限访问和学习模式，最大限度提高您通过公民考试的机会。',
    'gate.tier2Desc': '升级到Tier 2以获取翻译、视频指南和高级工具。',
    'gate.monthly': '每月',
    'gate.popular': '热门',
    'gate.perMonth': '/月',
    'gate.per6Months': '/6个月',
    'gate.tier1Cta': '解锁访问 — €6.99/月',
    'gate.tier2Cta': '升级到Premium — €10.99/月',
    'gate.later': '以后再说',
    'gate.feat1': '带有详细解释的学习模式',
    'gate.feat2': '无限不重复考试',
    'gate.feat3': '个性化进度跟踪',
    'gate.feat4': '有针对性的分类训练',
    'gate.feat5': 'CR和入籍级别',
    'gate.feat6': '实时题目翻译',
    'gate.feat7': '高级视频指南',
    'gate.feat8': '高级学习工具',
    'gate.feat9': '包含所有Standard权益',
    'nav.learn': '学习',
    'nav.account': '账户',
    'hero.startLearning': '开始学习',
    'learn.welcome': '欢迎回来，{name}！',
    'learn.subtitle': '今天想学什么？',
    'learn.continueLearning': '继续学习',
    'learn.learningPath': '我的学习路径',
    'learn.practiceTest': '练习与测试',
    'learn.myProgress': '我的进度',
    'learn.demoExam': '演示考试',
    'learn.fullExam': '完整考试',
    'learn.training': '训练模式',
    'learn.categoryTraining': '分类训练',
    'learn.lessonsCompleted': '已完成课程',
    'learn.accuracy': '准确率',
    'learn.examsTaken': '已参加考试',
    'learn.weakAreas': '薄弱领域',
    'learn.resume': '继续',
    'learn.nextLesson': '下一课',
    'learn.markComplete': '标记为完成',
    'learn.practice': '练习',
    'learn.locked': '需要订阅',
    'learn.upgrade': '升级到Standard',
    'learn.estimatedTime': '预计时间',
    'learn.backToLearn': '返回学习',
    'learn.completed': '已完成',
    'learn.allCompleted': '所有课程已完成！',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isBilingual: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.fr[key] || key;
  };

  const isBilingual = language !== 'fr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isBilingual }}>
      {children}
    </LanguageContext.Provider>
  );
}

const fallback: LanguageContextType = {
  language: 'fr',
  setLanguage: () => {},
  t: (key: string) => translations.fr[key] || key,
  isBilingual: false,
};

export function useLanguage() {
  const context = useContext(LanguageContext);
  return context ?? fallback;
}
