import { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '@/lib/types';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  fr: {
    'nav.home': 'Accueil',
    'nav.demo': 'Démo gratuite',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',
    'nav.dashboard': 'Tableau de bord',
    'nav.logout': 'Déconnexion',
    'hero.title': 'Préparez votre examen de citoyenneté',
    'hero.subtitle': 'La plateforme officielle pour réussir votre examen civique français en 2026',
    'hero.cta': 'Démo gratuite',
    'hero.cta2': 'Voir les prix',
    'pricing.title': 'Tarifs simples et transparents',
    'pricing.monthly': 'Mensuel',
    'pricing.semester': '6 Mois',
    'pricing.monthly.price': '6,99 €',
    'pricing.semester.price': '30,99 €',
    'pricing.feature1': 'Accès à toutes les questions',
    'pricing.feature2': 'Mode examen et étude',
    'pricing.feature3': 'Suivi de progression',
    'pricing.feature4': 'Questions bilingues',
    'pricing.cta': 'Commencer',
    'pricing.save': 'Économisez 26%',
    'quiz.question': 'Question',
    'quiz.of': 'sur',
    'quiz.next': 'Suivante',
    'quiz.prev': 'Précédente',
    'quiz.finish': 'Terminer',
    'quiz.timeRemaining': 'Temps restant',
    'quiz.study': 'Mode étude',
    'quiz.exam': 'Mode examen',
    'quiz.explanation': 'Explication',
    'quiz.correct': 'Bonne réponse !',
    'quiz.incorrect': 'Mauvaise réponse',
    'results.title': 'Résultats de l\'examen',
    'results.passed': 'RÉUSSI',
    'results.failed': 'ÉCHOUÉ',
    'results.score': 'Score',
    'results.time': 'Temps',
    'results.categories': 'Par catégorie',
    'results.retry': 'Réessayer',
    'results.home': 'Retour à l\'accueil',
    'results.passThreshold': 'Seuil de réussite : 80%',
    'auth.login': 'Connexion',
    'auth.signup': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.google': 'Continuer avec Google',
    'auth.or': 'ou',
    'auth.noAccount': 'Pas de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'footer.rights': '© 2026 Examen Civique. Tous droits réservés.',
  },
  en: {
    'nav.home': 'Home',
    'nav.demo': 'Free Demo',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'hero.title': 'Prepare for your citizenship exam',
    'hero.subtitle': 'The official platform to pass your French civic exam in 2026',
    'hero.cta': 'Free Demo',
    'hero.cta2': 'View Pricing',
    'pricing.title': 'Simple and transparent pricing',
    'pricing.monthly': 'Monthly',
    'pricing.semester': '6 Months',
    'pricing.monthly.price': '€6.99',
    'pricing.semester.price': '€30.99',
    'pricing.feature1': 'Access all questions',
    'pricing.feature2': 'Exam and study modes',
    'pricing.feature3': 'Progress tracking',
    'pricing.feature4': 'Bilingual questions',
    'pricing.cta': 'Get Started',
    'pricing.save': 'Save 26%',
    'quiz.question': 'Question',
    'quiz.of': 'of',
    'quiz.next': 'Next',
    'quiz.prev': 'Previous',
    'quiz.finish': 'Finish',
    'quiz.timeRemaining': 'Time remaining',
    'quiz.study': 'Study Mode',
    'quiz.exam': 'Exam Mode',
    'quiz.explanation': 'Explanation',
    'quiz.correct': 'Correct!',
    'quiz.incorrect': 'Incorrect',
    'results.title': 'Exam Results',
    'results.passed': 'PASSED',
    'results.failed': 'FAILED',
    'results.score': 'Score',
    'results.time': 'Time',
    'results.categories': 'By Category',
    'results.retry': 'Try Again',
    'results.home': 'Back to Home',
    'results.passThreshold': 'Pass threshold: 80%',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.google': 'Continue with Google',
    'auth.or': 'or',
    'auth.noAccount': 'No account?',
    'auth.hasAccount': 'Already have an account?',
    'footer.rights': '© 2026 Examen Civique. All rights reserved.',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.demo': 'تجربة مجانية',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'nav.dashboard': 'لوحة التحكم',
    'nav.logout': 'تسجيل الخروج',
    'hero.title': 'استعد لامتحان الجنسية',
    'hero.subtitle': 'المنصة الرسمية لاجتياز امتحان المدنية الفرنسي في 2026',
    'hero.cta': 'تجربة مجانية',
    'hero.cta2': 'عرض الأسعار',
    'pricing.title': 'أسعار بسيطة وشفافة',
    'pricing.monthly': 'شهري',
    'pricing.semester': '6 أشهر',
    'pricing.monthly.price': '٦٫٩٩ €',
    'pricing.semester.price': '٣٠٫٩٩ €',
    'pricing.feature1': 'الوصول لجميع الأسئلة',
    'pricing.feature2': 'وضع الامتحان والدراسة',
    'pricing.feature3': 'تتبع التقدم',
    'pricing.feature4': 'أسئلة ثنائية اللغة',
    'pricing.cta': 'ابدأ الآن',
    'pricing.save': 'وفر 26%',
    'quiz.question': 'سؤال',
    'quiz.of': 'من',
    'quiz.next': 'التالي',
    'quiz.prev': 'السابق',
    'quiz.finish': 'إنهاء',
    'quiz.timeRemaining': 'الوقت المتبقي',
    'quiz.study': 'وضع الدراسة',
    'quiz.exam': 'وضع الامتحان',
    'quiz.explanation': 'التفسير',
    'quiz.correct': 'إجابة صحيحة!',
    'quiz.incorrect': 'إجابة خاطئة',
    'results.title': 'نتائج الامتحان',
    'results.passed': 'ناجح',
    'results.failed': 'راسب',
    'results.score': 'النتيجة',
    'results.time': 'الوقت',
    'results.categories': 'حسب الفئة',
    'results.retry': 'إعادة المحاولة',
    'results.home': 'العودة للرئيسية',
    'results.passThreshold': 'حد النجاح: 80%',
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.google': 'المتابعة مع جوجل',
    'auth.or': 'أو',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'footer.rights': '© 2026 Examen Civique. جميع الحقوق محفوظة.',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.demo': 'Demo gratis',
    'nav.login': 'Iniciar sesión',
    'nav.signup': 'Registrarse',
    'nav.dashboard': 'Panel',
    'nav.logout': 'Cerrar sesión',
    'hero.title': 'Prepara tu examen de ciudadanía',
    'hero.subtitle': 'La plataforma oficial para aprobar tu examen cívico francés en 2026',
    'hero.cta': 'Demo gratis',
    'hero.cta2': 'Ver precios',
    'pricing.title': 'Precios simples y transparentes',
    'pricing.monthly': 'Mensual',
    'pricing.semester': '6 Meses',
    'pricing.monthly.price': '6,99 €',
    'pricing.semester.price': '30,99 €',
    'pricing.feature1': 'Acceso a todas las preguntas',
    'pricing.feature2': 'Modo examen y estudio',
    'pricing.feature3': 'Seguimiento del progreso',
    'pricing.feature4': 'Preguntas bilingües',
    'pricing.cta': 'Empezar',
    'pricing.save': 'Ahorra 26%',
    'quiz.question': 'Pregunta',
    'quiz.of': 'de',
    'quiz.next': 'Siguiente',
    'quiz.prev': 'Anterior',
    'quiz.finish': 'Terminar',
    'quiz.timeRemaining': 'Tiempo restante',
    'quiz.study': 'Modo estudio',
    'quiz.exam': 'Modo examen',
    'quiz.explanation': 'Explicación',
    'quiz.correct': '¡Correcto!',
    'quiz.incorrect': 'Incorrecto',
    'results.title': 'Resultados del examen',
    'results.passed': 'APROBADO',
    'results.failed': 'SUSPENDIDO',
    'results.score': 'Puntuación',
    'results.time': 'Tiempo',
    'results.categories': 'Por categoría',
    'results.retry': 'Reintentar',
    'results.home': 'Volver al inicio',
    'results.passThreshold': 'Umbral de aprobación: 80%',
    'auth.login': 'Iniciar sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.google': 'Continuar con Google',
    'auth.or': 'o',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'footer.rights': '© 2026 Examen Civique. Todos los derechos reservados.',
  },
  pt: {
    'nav.home': 'Início',
    'nav.demo': 'Demo grátis',
    'nav.login': 'Entrar',
    'nav.signup': 'Registar',
    'nav.dashboard': 'Painel',
    'nav.logout': 'Sair',
    'hero.title': 'Prepare o seu exame de cidadania',
    'hero.subtitle': 'A plataforma oficial para passar no exame cívico francês em 2026',
    'hero.cta': 'Demo grátis',
    'hero.cta2': 'Ver preços',
    'pricing.title': 'Preços simples e transparentes',
    'pricing.monthly': 'Mensal',
    'pricing.semester': '6 Meses',
    'pricing.monthly.price': '6,99 €',
    'pricing.semester.price': '30,99 €',
    'pricing.feature1': 'Acesso a todas as questões',
    'pricing.feature2': 'Modo exame e estudo',
    'pricing.feature3': 'Acompanhamento do progresso',
    'pricing.feature4': 'Questões bilíngues',
    'pricing.cta': 'Começar',
    'pricing.save': 'Poupe 26%',
    'quiz.question': 'Questão',
    'quiz.of': 'de',
    'quiz.next': 'Seguinte',
    'quiz.prev': 'Anterior',
    'quiz.finish': 'Terminar',
    'quiz.timeRemaining': 'Tempo restante',
    'quiz.study': 'Modo estudo',
    'quiz.exam': 'Modo exame',
    'quiz.explanation': 'Explicação',
    'quiz.correct': 'Correto!',
    'quiz.incorrect': 'Incorreto',
    'results.title': 'Resultados do exame',
    'results.passed': 'APROVADO',
    'results.failed': 'REPROVADO',
    'results.score': 'Pontuação',
    'results.time': 'Tempo',
    'results.categories': 'Por categoria',
    'results.retry': 'Tentar novamente',
    'results.home': 'Voltar ao início',
    'results.passThreshold': 'Limiar de aprovação: 80%',
    'auth.login': 'Entrar',
    'auth.signup': 'Registar',
    'auth.email': 'Email',
    'auth.password': 'Palavra-passe',
    'auth.google': 'Continuar com Google',
    'auth.or': 'ou',
    'auth.noAccount': 'Não tem conta?',
    'auth.hasAccount': 'Já tem conta?',
    'footer.rights': '© 2026 Examen Civique. Todos os direitos reservados.',
  },
  zh: {
    'nav.home': '首页',
    'nav.demo': '免费试用',
    'nav.login': '登录',
    'nav.signup': '注册',
    'nav.dashboard': '仪表板',
    'nav.logout': '退出',
    'hero.title': '准备您的公民考试',
    'hero.subtitle': '2026年通过法国公民考试的官方平台',
    'hero.cta': '免费试用',
    'hero.cta2': '查看价格',
    'pricing.title': '简单透明的定价',
    'pricing.monthly': '每月',
    'pricing.semester': '6个月',
    'pricing.monthly.price': '€6.99',
    'pricing.semester.price': '€30.99',
    'pricing.feature1': '访问所有题目',
    'pricing.feature2': '考试和学习模式',
    'pricing.feature3': '进度跟踪',
    'pricing.feature4': '双语题目',
    'pricing.cta': '开始',
    'pricing.save': '节省26%',
    'quiz.question': '问题',
    'quiz.of': '/',
    'quiz.next': '下一题',
    'quiz.prev': '上一题',
    'quiz.finish': '完成',
    'quiz.timeRemaining': '剩余时间',
    'quiz.study': '学习模式',
    'quiz.exam': '考试模式',
    'quiz.explanation': '解释',
    'quiz.correct': '正确！',
    'quiz.incorrect': '错误',
    'results.title': '考试结果',
    'results.passed': '通过',
    'results.failed': '未通过',
    'results.score': '分数',
    'results.time': '时间',
    'results.categories': '按类别',
    'results.retry': '重试',
    'results.home': '返回首页',
    'results.passThreshold': '及格线：80%',
    'auth.login': '登录',
    'auth.signup': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.google': '使用Google继续',
    'auth.or': '或',
    'auth.noAccount': '没有账户？',
    'auth.hasAccount': '已有账户？',
    'footer.rights': '© 2026 Examen Civique. 保留所有权利。',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isBilingual: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.fr[key] || key;
  };

  const isBilingual = language !== 'fr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isBilingual }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
