UPDATE public.questions SET question_translated = 'What is the motto of the Republic?' WHERE question_fr = 'Quelle est la devise de la République ?';
UPDATE public.questions SET question_translated = 'What is the emblem of the Republic?' WHERE question_fr = 'Quel est l''emblème de la République ?';
UPDATE public.questions SET question_translated = 'Marianne is a figure that represents:' WHERE question_fr = 'Marianne est une figure qui représente :';
UPDATE public.questions SET question_translated = 'What is the meaning of Laïcité (Secularism)?' WHERE question_fr = 'Quelle est la signification de la Laïcité ?';
UPDATE public.questions SET question_translated = 'Can someone be forced to marry in France?' WHERE question_fr = 'Peut-on être forcé à se marier en France ?';
UPDATE public.questions SET question_translated = 'What is the minimum age for marriage in France?' WHERE question_fr = 'Quel est l''âge minimum du mariage en France ?';
UPDATE public.questions SET question_translated = 'Who votes the laws in France?' WHERE question_fr = 'Qui vote les lois en France ?';
UPDATE public.questions SET question_translated = 'Who is the head of the Executive power?' WHERE question_fr = 'Qui est le chef du pouvoir exécutif ?';
UPDATE public.questions SET question_translated = 'What is the role of the Constitutional Council?' WHERE question_fr = 'Quel est le rôle du Conseil constitutionnel ?';
UPDATE public.questions SET question_translated = 'France is a member of the European Union since:' WHERE question_fr = 'La France est membre de l''Union européenne depuis :';
UPDATE public.questions SET question_translated = 'What right guarantees the freedom to choose one''s religion?' WHERE question_fr = 'Quel droit garantit la liberté de choisir sa religion ?';
UPDATE public.questions SET question_translated = 'At what age is schooling mandatory in France?' WHERE question_fr = 'À quel âge la scolarité est-elle obligatoire en France ?';
UPDATE public.questions SET question_translated = 'What major event happened in France in 1789?' WHERE question_fr = 'Quel événement majeur s''est passé en France en 1789 ?';
UPDATE public.questions SET question_translated = 'The Eiffel Tower was built for:' WHERE question_fr = 'La Tour Eiffel a été construite pour :';
UPDATE public.questions SET question_translated = 'Which mountain range separates France from Spain?' WHERE question_fr = 'Quelle chaîne de montagnes sépare la France de l''Espagne ?';
UPDATE public.questions SET question_translated = 'What document must a foreigner present to reside legally in France?' WHERE question_fr = 'Quel document un étranger doit-il présenter pour résider légalement en France ?';
UPDATE public.questions SET question_translated = 'Social Security in France covers:' WHERE question_fr = 'La Sécurité sociale en France couvre :';
UPDATE public.questions SET question_translated = 'The legal working time in France is:' WHERE question_fr = 'La durée légale du travail en France est de :';
UPDATE public.questions SET question_translated = 'Public education in France is:' WHERE question_fr = 'L''enseignement public en France est :';
UPDATE public.questions SET question_translated = 'What is the French national anthem?' WHERE question_fr = 'Quel est l''hymne national français ?';